# Generated by Django 4.1.7 on 2023-03-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceries_new", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereduser",
            name="profilePic",
            field=models.ImageField(default="default.jpeg", upload_to="profile_pics"),
        ),
    ]
